### ISSUE TITLE
litecoin-node-status.py can't connect to the application

### ISSUE THREAD

**Issue by pdroalves** [litecoin-association/LitecoinNode#27]
When /home/litecoind/scripts/litecoin-node-status.py is executed, it returns:
```
Traceback (most recent call last):
  File "/home/litecoind/scripts/litecoin-node-status.py", line 12, in <module>
    lcd_data = get_lcd_info.getinfo()
  File "/usr/local/lib/python2.7/dist-packages/bitcoinrpc/authproxy.py", line 112, in __call__
    'Content-type': 'application/json'})
  File "/usr/lib/python2.7/httplib.py", line 1017, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1051, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1013, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 864, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 826, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 807, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 571, in create_connection
    raise err
socket.error: [Errno 111] Connection refused

```
I'm running the script on a clean Ubuntu 14.04 installation.

**Comment by losh11** [comment]
Looks like something to do with the RPC connection. Check the passphrase/ports.

**Comment by pdroalves** [comment]
@losh11 This happens when executed inside the script to install on Linux. I didn't changed the passphrase or ports.
